# Generated by Django 4.0.5 on 2022-09-25 21:43

import core.s3_options
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 일자')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정 일자')),
                ('title', models.CharField(max_length=30)),
                ('content', models.TextField()),
                ('category', models.CharField(choices=[('etc', 'etc'), ('game', 'game'), ('develop', 'develop'), ('study', 'study')], default='etc', max_length=30)),
                ('status', models.CharField(choices=[('public', 'public'), ('private', 'private')], default='public', max_length=7)),
                ('photo', models.FileField(blank=True, null=True, upload_to=core.s3_options.content_image_path, verbose_name='사진')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'post',
            },
        ),
    ]
