version: "3"
services:
  # mysql-server
  mysql:
    container_name: board-mysql
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: p@ssword
      MYSQL_DATABASE: board
      MYSQL_TZ: Asia/Seoul
    ports:
      - 3310:3306
    volumes:
      - ./mysql:/var/lib/mysql

  # redis-server
  redis:
    container_name: "board-redis"
    image: redis:latest
    restart: always
    command: redis-server /usr/local/conf/redis.conf
    volumes:
      - ./redis/data/:/data
      - ./redis/conf/redis.conf:/usr/local/conf/redis.conf
    ports:
      - 6380:6379
