# Generated by Django 4.0.5 on 2022-09-26 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='Board',
            new_name='post',
        ),
    ]
