# Generated by Django 4.0.5 on 2022-09-26 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['created_at'], 'verbose_name': '회원', 'verbose_name_plural': 'User'},
        ),
    ]
