# Generated by Django 4.0.5 on 2022-09-04 00:26

import core.s3_options
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.FileField(blank=True, default='images/profile/default.jpg', null=True, upload_to=core.s3_options.image_path, verbose_name='사진'),
        ),
    ]
